"""Beaconing detection methods."""

# scikit-learn is a required project dependency now that anomaly detectors are
# first-class baselines alongside the rule and statistical detectors.
from .anomaly import (
    DEFAULT_ANOMALY_FEATURES,
    ISOLATION_FOREST_NAME,
    LOCAL_OUTLIER_FACTOR_NAME,
    AnomalyContribution,
    AnomalyDetectionResult,
    AnomalyDetectorConfig,
    AnomalyDetectorModel,
    AnomalyDetectorType,
    detect_flow_feature_rows_anomaly,
    detect_flow_features_anomaly,
    fit_anomaly_detector,
    score_flow_features_anomaly,
)
from .rules import (
    FROZEN_RULE_BASELINE_NAME,
    FROZEN_RULE_BASELINE_THRESHOLDS,
    HIGH_PRECISION_RULE_BASELINE_THRESHOLDS,
    RuleContribution,
    RuleDetectionResult,
    RuleThresholds,
    detect_flow_feature_rows,
    detect_flow_features,
)
from .statistical import (
    DEFAULT_STATISTICAL_FEATURES,
    FeatureReference,
    StatisticalBaselineConfig,
    StatisticalBaselineModel,
    STATISTICAL_BASELINE_NAME,
    StatisticalContribution,
    StatisticalDetectionResult,
    detect_flow_feature_rows_statistical,
    detect_flow_features_statistical,
    fit_statistical_baseline,
    score_flow_features,
)
from .supervised import (
    DEFAULT_SUPERVISED_FEATURES,
    LOGISTIC_REGRESSION_NAME,
    RANDOM_FOREST_NAME,
    SupervisedContribution,
    SupervisedDetectionResult,
    SupervisedDetectorConfig,
    SupervisedDetectorModel,
    SupervisedDetectorType,
    detect_flow_feature_rows_supervised,
    detect_flow_features_supervised,
    fit_supervised_detector,
    supervised_operating_point,
)

__all__ = [
    "DEFAULT_ANOMALY_FEATURES",
    "DEFAULT_SUPERVISED_FEATURES",
    "DEFAULT_STATISTICAL_FEATURES",
    "FeatureReference",
    "FROZEN_RULE_BASELINE_NAME",
    "FROZEN_RULE_BASELINE_THRESHOLDS",
    "HIGH_PRECISION_RULE_BASELINE_THRESHOLDS",
    "ISOLATION_FOREST_NAME",
    "LOCAL_OUTLIER_FACTOR_NAME",
    "LOGISTIC_REGRESSION_NAME",
    "RANDOM_FOREST_NAME",
    "AnomalyContribution",
    "AnomalyDetectionResult",
    "AnomalyDetectorConfig",
    "AnomalyDetectorModel",
    "AnomalyDetectorType",
    "RuleContribution",
    "RuleDetectionResult",
    "RuleThresholds",
    "StatisticalBaselineConfig",
    "StatisticalBaselineModel",
    "STATISTICAL_BASELINE_NAME",
    "StatisticalContribution",
    "StatisticalDetectionResult",
    "SupervisedContribution",
    "SupervisedDetectionResult",
    "SupervisedDetectorConfig",
    "SupervisedDetectorModel",
    "SupervisedDetectorType",
    "detect_flow_feature_rows",
    "detect_flow_feature_rows_anomaly",
    "detect_flow_feature_rows_statistical",
    "detect_flow_feature_rows_supervised",
    "detect_flow_features",
    "detect_flow_features_anomaly",
    "detect_flow_features_statistical",
    "detect_flow_features_supervised",
    "fit_anomaly_detector",
    "fit_statistical_baseline",
    "fit_supervised_detector",
    "score_flow_features_anomaly",
    "score_flow_features",
    "supervised_operating_point",
]
